# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9ec842030e05ed8252a72cd00597e32f1d2518085d2486f3035528340252135c1e7ae9c411cf796d4238e1c56802f8654298324b3ebbb7f7a66adb6af4a04a9

test:
  secret_key_base: a1669970dc48cc9c55bae0fc6495b3dc32b9a07a7dabf87f095180636fef3c24f5e79fb37c3ced752d7860d907dc1110820dda3efc74756a60bd19d48dbf97b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
